name: Refresh Spotify Token and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to the repository contents

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: List Files for Debugging
      run: ls -la  # Lists files to ensure the correct file paths

    - name: Refresh Spotify Access Token
      id: get-token
      run: |
        CLIENT_ID=${{ secrets.CLIENT_ID }}
        CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
        AUTH_HEADER=$(echo -n "$CLIENT_ID:$CLIENT_SECRET" | base64)
        echo "Authorization Header: $AUTH_HEADER"
        RESPONSE=$(curl -s -X POST -H "Authorization: Basic $AUTH_HEADER" /
        -d grant_type=client_credentials /
        https://accounts.spotify.com/api/token)
        echo "Response: $RESPONSE"
        ERROR=$(echo "$RESPONSE" | jq -r .error)
        ERROR_DESCRIPTION=$(echo "$RESPONSE" | jq -r .error_description)
        echo "Error: $ERROR"
        echo "Error Description: $ERROR_DESCRIPTION"
        TOKEN=$(echo "$RESPONSE" | jq -r .access_token)
        echo "Access Token: $TOKEN"
        echo "TOKEN=${TOKEN}" >> $GITHUB_ENV

    - name: Debug Access Token
      run: echo "Token from environment ${{ env.TOKEN }}"

    - name: Update Access Token in JavaScript
      run: |
        echo "Before replacement:"
        cat ./app.js  # Display the file before modification
        sed -i "s/const accessToken = '.*'/const accessToken = '${{ env.TOKEN }}'/g" ./app.js
        echo "After replacement:"
        cat ./app.js  # Display the file after modification

    - name: Commit and Push Changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add ./app.js
        git commit -m "Update Spotify access token"
        git push origin main  # Ensure you push to the correct branch

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Adjust to your actual build output directory
